module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  setupFiles: ['../jest.setup.js'],
  setupFilesAfterEnv: ['<rootDir>/common/__tests__/setup.ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  maxWorkers: 1, // Run tests sequentially to avoid BigInt serialization issues
  transform: {
    '^.+\\.(t|j)s$': ['ts-jest', {
      tsconfig: {
        allowSyntheticDefaultImports: true,
        esModuleInterop: true,
        experimentalDecorators: true,
        emitDecoratorMetadata: true,
        strictNullChecks: true,
        noImplicitAny: true,
        skipLibCheck: true,
      },
      isolatedModules: true,
    }],
  },
  collectCoverageFrom: [
    '<rootDir>/**/*.ts',
    '!<rootDir>/**/*.spec.ts',
    '!<rootDir>/**/index.ts',
    '!<rootDir>/**/*.module.ts',
    '!<rootDir>/**/dto/**',
    '!<rootDir>/**/processors/**',
    '!<rootDir>/main.ts',
    '!<rootDir>/lambda.ts',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^@auth/(.*)$': '<rootDir>/auth/$1',
    '^@booking/(.*)$': '<rootDir>/booking/$1',
    '^@voice/(.*)$': '<rootDir>/voice/$1',
    '^@customer/(.*)$': '<rootDir>/customer/$1',
    '^@common/(.*)$': '<rootDir>/common/$1',
    '^@gdpr/(.*)$': '<rootDir>/gdpr/$1',
    '(.*)/types/express$': '<rootDir>/types/__mocks__/express',
  },
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/__tests__/',
    '/examples/',
    'instrument\\.ts$',
    'telemetry\\.ts$',
    'config/env\\.ts$',
    'services/pivaService\\.ts$',
    'services/external/',
    '\\.d\\.ts$',
  ],
  coverageReporters: ['text', 'text-summary', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
};
